version: '3.8'

networks:
  default:
    name: sdd-net

services:
  database:
    container_name: database
    image: postgres:12.6
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: sdd
    ports:
      - 5432:5432

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=sdd
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor