spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sdd
    username: root
    password: toor
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy