spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sdd
    username: root
    password: toor
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy